os: osx
osx_image: xcode11.3
language: swift

addons:
  homebrew:
    packages:
    - swiftgen
    - swiftlint
    - nvm

xcode_project: Roadie iOS.xcodeproj
xcode_scheme: Roadie
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro

jobs:
  include:
    - stage: releasee
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - nvm install lts/*
          - npx semantic-release
        on:
          all_branches: true

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Roadie'

