os: osx
osx_image: xcode11.3
language: swift

addons:
  homebrew:
    packages:
    - swiftgen
    - swiftlint
    - nvm

xcode_project: Roadie iOS.xcodeproj
xcode_scheme: Roadie
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro

jobs:
  include:
    - stage: Release
      deploy:
        script: skip # don't rerun tests
        provider: script
        script: deploy.sh
        if: branch = master

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Roadie'

